### ==========================================
### CONTEXT DEMOS
### ==========================================

### Request Demos
GET http://{{url}}/context_request_demo

###
GET http://{{url}}/context_request_demo/pathparam/ThomasHartmann

###
GET http://{{url}}/context_request_demo/queryparam?qp=MyQueryParam

###
GET http://{{url}}/context_request_demo/header
X-EXAMPLE-HEADER: MyHeaderValue

###
GET http://{{url}}/context_request_demo/req

### Response Demos
GET http://{{url}}/context_response_demo/contenttype

###
GET http://{{url}}/context_response_demo/header

###
GET http://{{url}}/context_response_demo/status

###
GET http://{{url}}/context_response_demo/json

###
GET http://{{url}}/context_response_demo/html

###
GET http://{{url}}/context_response_demo/render

### ==========================================
### USERS & AUTH
### ==========================================

### ==========================================
### USERS & AUTH ROUTES
### ==========================================

### Login (get token)
POST http://{{url}}/auth/login
Content-Type: application/json

{
  "userName": "Philip TEST",
  "password": "pass12345"
}

> {% client.global.set("token", response.body.token); %}

### User demo (requires USER role)
GET http://{{url}}/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlBoaWxpcCBTdW5lIE5pbGF1c2VuXCIiLCJzdWIiOiJQaGlsaXAgVEVTVCIsImV4cCI6MTc1OTU3NDk5Mywicm9sZXMiOiJVc2VyIiwidXNlcm5hbWUiOiJQaGlsaXAgVEVTVCJ9.sa-74j0Lx12wbhPPnmhAjDewXeQUoPL2gLPhpmlMLX8

### Admin demo (requires ADMIN role)
GET http://{{url}}/protected/admin_demo
Authorization: Bearer {{token}}
